### ISSUE TITLE
Uppercase shortcut does not working.

### ISSUE THREAD

**Issue by Teo-Cardoso** [eduidl/rtui#3]
The shortcut keys are shown as uppercase letters, however, when uppercase is enabled the shortcuts don't work.
I see four ways of dealing with this:

1. Add the uppercase and keep the lowercase letters as well
2. Remove lowercase shortcuts and add the uppercase letters
3. Change the letters on the UI to lowercase and keep the shortcuts in lowercase letters
4. Don't change anything and keep it this way

![image](https://user-images.githubusercontent.com/34777371/178618479-452d4bb0-65fd-4c9e-997f-998d2b777c6c.png)

**Comment by eduidl** [comment]
@Teo-Cardoso
Thank you for your feedback!
This is the default specification of the TUI library, textual, and I did not intend to make the display and behavior inconsistent. I'm going to choose the third options.
I'm fixing this issue in https://github.com/eduidl/rtui/pull/4.

**Comment by eduidl** [comment]
![image](https://user-images.githubusercontent.com/25898373/178630849-20cc994d-52e4-439f-9b50-b40fcf6df039.png)
